# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e061fc36d2685d562d220e93fd1bfdeb18f191d18f27b04f3caf98e12514370ede00bd38cab04d7905a722f4f2a23f0e535f259c4b64290a3e791e87253dc75

test:
  secret_key_base: 3624a4a8934ce2ea16bf5939232898b4278266c04f986cc1f4368acb26cb498bfa477d933479ec0005db27db50489df2c99ff53e63157e17213cf0c0c1a86c98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
